version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: body_language_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    restart: unless-stopped
    env_file: ./api/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs
    environment:
      - NODE_ENV=production

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=production

  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - web

volumes:
  postgres-data:
