# railway.toml
# Railway.app deployment configuration

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "api"
buildCommand = "npm ci && npx prisma generate && npx prisma migrate deploy"
startCommand = "npm start"
healthcheckPath = "/api/health"
port = 5000

[[services]]
name = "web"
source = "web"
buildCommand = "npm ci && npm run build"
startCommand = "npm run preview"
port = 4173
