# render.yaml
# Render.com deployment configuration for AI Body Language Decoder

services:
  # PostgreSQL Database
  - type: psql
    name: body-language-db
    plan: starter
    databaseName: body_language_db
    user: postgres
    region: oregon

  # API Backend
  - type: web
    name: body-language-api
    env: node
    plan: starter
    region: oregon
    buildCommand: cd api && npm ci && npx prisma generate && npx prisma migrate deploy
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: body-language-db
          property: connectionString
      - key: PORT
        value: 5000
    healthCheckPath: /api/health

  # React Frontend
  - type: web
    name: body-language-web
    env: static
    plan: starter
    region: oregon
    buildCommand: cd web && npm ci && npm run build
    staticPublishPath: ./web/dist
    envVars:
      - key: VITE_API_URL
        value: https://body-language-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
